version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: 01_backend_registration/docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./01_backend_registration/app/logs:/app/logs
    environment:
      - FLASK_ENV=development