version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      EXTERNAL_API_URL: "http://176.192.70.122:90/fitnes_t_nfc_mobile/hs/nfc_mobile/v1"
      EXTERNAL_LOGIN: "FitnessKit"
      EXTERNAL_PASSWORD: "vY0xodyg"
      EXTERNAL_CLUB_ID: "59115d1e-9052-11eb-810c-6eae8b56243b"
    command: gunicorn project_name.wsgi:application --bind 0.0.0.0:8000
